### PR TITLE
Basic python build environment

### PR DESCRIPTION
**Pull request by neekolas**
Adds libffi-devel and Python C bindings.

### CODE REVIEW

**Comment by neekolas** [comment]
Only python27-devel is explicitly for Python deps, so we could move some of the other dependencies to the base build. I can make bcrypt compile fine in node without libffi-devel, but installing from pip blows up without it.

**Comment by mhart** [comment]
Nice, I'm down with this 👍 

I'll check it out locally and possibly move stuff around (perhaps to the base image as you suggested)

**Comment by mhart** [comment]
Awesome! I moved some stuff around and tested `pip install bcrypt` – seemed to work fine 👍 

Just pushing latest build image now – should be up soon – I'll comment again when it is

**Comment by mhart** [comment]
(docker push is currently stalled for some reason)

**Comment by mhart** [comment]
Ok, both `lambci/lambda-base:build` and `lambci/lambda:build-python2.7` should be up to date now.

Let me know if that works for you – and thanks for the contribution!

**Comment by neekolas** [comment]
Awesome. Will test it out tonight.

Really appreciate this resource. Prior to docker-lambda we did all of our Lambda Circle builds using a Frankenstein-like Dockerfile that tried to recreate the Lambda environment. Had to compile practically everything in the build toolchain from source, which was a total nightmare to maintain or modify. Moved most of our projects over last week and it's been great so far.

**Pull request merged**
