### PR TITLE
Install Bundler on build image

### PR DESCRIPTION
**Pull request by ojongerius**

### CODE REVIEW

**Comment by ojongerius** [comment]
Awesome, interested to see what caused it!

**Comment by mhart** [comment]
Well `/var/runtime/bin` *isn't* added to PATH in Lambda – I have no idea why Amazon put bundler there.

I actually think this is a better solution than adding `/var/runtime/bin` to the PATH, so I'm going to reopen this.

**Comment by mhart** [comment]
Just pushed out a new version of `build-ruby2.5` with this included – thanks for the contribution!

**Comment by ojongerius** [comment]
Thanks for the quick turnaround!

**Pull request merged**
