### PR TITLE
Bump go version to 1.11.5 in build image

### PR DESCRIPTION
**Pull request by adamlc**
Just bumping to the go build image to the latest version.

### CODE REVIEW

**Comment by mhart** [comment]
Thanks for this, sorry it took a while to get to – I updated to 1.12 in 4876d913b61ab820f32599c692d9a4d7a7bca75c

**Comment by adamlc** [comment]
@mhart cool thanks! Does the docker image on docker hub need rebuilding? Its still 1.11.2 there.

**Comment by mhart** [comment]
Ugh, is it? I thought it was rebuilt at the time...

Screen Shot 2019-03-20 at 12 09 03 pm

Lemme check out what's going on

**Comment by adamlc** [comment]
Hmm odd!

```bash
$ docker pull lambci/lambda:build-go1.x
build-go1.x: Pulling from lambci/lambda
6db477c4ae19: Already exists
816c0e38dd00: Already exists
115f683df8ea: Already exists
3c48095bb955: Already exists
161b6612e711: Already exists
Digest: sha256:f0f1cc53356238a27226140df7d6ead49aa587acf8e5134d4d2bb4f09ac56792
Status: Image is up to date for lambci/lambda:build-go1.x

$ docker run --rm -it lambci/lambda:build-go1.x go version
go version go1.11.2 linux/amd64
```

**Comment by mhart** [comment]
Yeah, seems like I forgot to update the git tag. Just pushed the latest image now – sorry for the hassle!

**Pull request closed without merging**
