### PR TITLE
Install Amazon Lambda Global Tools by Default

### PR DESCRIPTION
**Pull request by chrisoverzero**
...and also correct a bug related to setting the environment

Fixes bug introduced in https://github.com/lambci/docker-lambda/pull/156.

### CODE REVIEW

**Comment by mhart** [comment]
Actually just pushed a fix (reordered the PATH too – better to have more specific directories earlier in the path IMO) – so you'll need to rebase again :-)

**Comment by chrisoverzero** [comment]
🎉 Thanks so much!

**Comment by mhart** [comment]
(building now, will let you know when published – thanks for the contribution!)

**Comment by mhart** [comment]
Published!

**Pull request merged**
