### PR TITLE
Add lambda api to keep runtimes warm

### PR DESCRIPTION
**Pull request by mhart**
Addresses #14

- [x] address all error cases
- [x] make port configurable
- [x] add support for log tailing to all runtimes
- [x] test that original (non-warm) cases work as per usual
- [ ] clean up code

### CODE REVIEW

**Comment by mhart** [comment]
This is done as of f802a10618ff1bc4f814bba5fd504a35d5ad0bad

All old images were published using `20191117-<runtime>` tags, eg `lambci/lambda:20191117-dotnetcore2.1`

**Comment by tprimini-daitan** [comment]
> 20191117-

@mhart are you able to push a 20191117-nodejs12.x to docker hub? localstack is referencing this name, at least for now.

**Comment by mhart** [comment]
@tprimini-daitan localstack shouldn't be referencing that name – there was no `20191117-nodejs12.x`, the runtimes weren't released until a day or so later

**Comment by tprimini-daitan** [comment]
That is confused, take a look here: https://github.com/localstack/localstack/blob/1272a833b6d00841369bd195e76e28c84b2823b1/localstack/services/awslambda/lambda_executors.py#L690

**Comment by mhart** [comment]
@tprimini-daitan I don't have any relation to localstack – they just happen to have used a whole bunch of my software (dynalite, kinesalite, docker-lambda).

Looks like you should probably open up an issue there – maybe they don't support nodejs12.x yet

**Comment by tprimini-daitan** [comment]
> @tprimini-daitan I don't have any relation to localstack – they just happen to have used a whole bunch of my software (dynalite, kinesalite, docker-lambda).
> 
> Looks like you should probably open up an issue there – maybe they don't support nodejs12.x yet

@mhart thank you so much for your attention and time.

**Pull request closed without merging**
