### PR TITLE
Wait for stdout flush in before exiting in nodejs

### PR DESCRIPTION
**Pull request by tmo-trustpilot**
I'm trying to test a lambda that returns a base64 encoded binary response which is supported by the API Gateway lambda proxy but the responses are getting truncated when writing to stdout.

This workaround follows the example in the `writable.write` documentation: https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback

### CODE REVIEW

**Comment by tmo-trustpilot** [comment]
@mhart Any chance you could take a look at this?

**Comment by mhart** [comment]
@tmo-trustpilot yeah, dropped the ball on this, sorry – will try to get to this by the weekend

**Comment by philipnilsson** [comment]
@mhart Any chance you'll have time to merge this? Right now any output gets cut off at 65536 characters which isn't too great if you're generating screenshots.

**Comment by miklosaubert** [comment]
@mhart Please have a look at this, the problem is also there in nodejs 6.10. I also had to add some missing methods on the mocks, not sure if this is the right way to go but it did the trick for me.

**Comment by mhart** [comment]
Thanks for this! Just finished building on Docker hub now. I cherry picked your flush commits (had fixed the missing method stubs already before seeing this).

Thanks again for the contribution 👍

**Comment by tmo-trustpilot** [comment]
@mhart Thanks! And thanks for your work maintaining this project.

**Pull request closed without merging**
