### PR TITLE
Support passing extra arguments to bootstrap file of 'provided' runtimes

### PR DESCRIPTION
**Pull request by sanathkr**
AWS SAM CLI will use this mechanism to customize what and how the bootstrap gets invoked.
We want to use this to start the language runtime or bootstrap in debug mode.

For Python 3.7, we will invoke the entrypoint as follows:
```bash
/var/rapid/init \
    --bootstrap /var/lang/bin/python3.7 \
    --bootstrap-args '["-u", "/tmp/lambci_debug_files/pydevd.py", "--multiprocess", "--port", "58381", "--file", "/var/runtime/bootstrap"]'
```

For other programming languages (say Nodejs), we might need to create a separate bootstrap
file that starts the node interpretor with debug args. In this case I anticipate us to invoke
using a command similar to this:

```bash
/var/rapid/init \
    --bootstrap /var/runtime/bootstrap.debug \
    --bootstrap-args '["--inspect-brk", "0.0.0.0:9090"]'
```

### CODE REVIEW

**Comment by mhart** [comment]
Yeah, nice, this is exactly the sort of approach I was hoping we'd settle on

**Comment by billyshambrook** [comment]
This is great, any reason for this to still be in draft?

**Comment by sanathkr** [comment]
Just published the PR now.

**Comment by mhart** [comment]
Awesome, looks good to me – will merge and let you know when this has been published

**Comment by mhart** [comment]
Done! Pushed updated images for `provided`, `ruby2.5` and `python3.7`

**Comment by sanathkr** [comment]
Awesome! Thanks for the quick turn around

**Pull request merged**
